geofence/models.py
# -*- coding: utf-8 -*-

from django.contrib.gis.db import models
from itrack.system.models import System
from itrack.equipments.models import Equipment
# from itrack.alerts.models import Alert

class Geofence(models.Model):
    name = models.CharField(max_length=200,verbose_name = 'Nome da cerca eletrônica',blank=True)
    system = models.ForeignKey(System, verbose_name = "Sistema")
    # alert = models.ForeignKey(Alert, verbose_name = "Alerta",null = True)
    types = (
            ('C', 'Círculo'),
            ('P', 'Polígono'),
            ('R', 'Rota')
        )
    type = models.CharField(max_length=1, choices=types)
    polygon = models.PolygonField(null = True,blank=True)
    linestring = models.LineStringField(null = True,blank=True)
    tolerance = models.PositiveIntegerField(null=True,blank=True)
    objects = models.GeoManager()

    def __unicode__(self):
        return str(self.name)

geofence/templates/create_finish.html
{% extends "templates/base.html" %}

{%block title%}Infotrack - Criação de Cerca eletrônica {% endblock %}
{% block content %}


<div  class="main-form">
<h1><img class="icon" src="/media/img/equipment.png">Criação de Cerca eletrônica</h1>
<hr />
<h2>Cerca eletrônica finalizada com sucesso </h2>
<em>A Cerca eletrônica foi criada com sucesso. <a href="{% url geofence.views.index %}"> Clique aqui para voltar a tela de administração de Cercas eletrônicas. </a></em>

</div>
{% endblock %}

geofence/templates/delete.html
{% extends "templates/base.html" %}

{% block content  %}

<div class="main-form">
  <h1><img class="icon" src="/media/img/equipment.png">Gerenciamento de Cercas eletrônicas</h1>
  <hr />
					<h2>Remoção de Cerca eletrônica</h2>
					<em> Tem certeza que deseja remover a cerca eletrônica "{{ g.name }}"? </em>
					
					<div align="center" style="margin-top:10px;" id="actions">
            
            <form action='.' method='post'>{% csrf_token %}
                <a href="#" onClick="parentNode.submit();">Confirmar</a>
                <a onClick="history.back();">Cancelar</a>
            </form>
            </div>

{% endblock %}

geofence/templates/delete_finish.html
{% extends "templates/base.html" %}

{%block title%}Infotrack - Remoção de Cerca eletrônica {% endblock %}

{% block content %}


<div  class="main-form">
<h1><img class="icon" src="/media/img/equipment.png">Remoção de Cerca eletrônica</h1>
<hr />
<h2> Remoção finalizada com sucesso </h2>
<em>A Cerca eletrônica foi removida do sistema. <a href="{% url geofence.views.index %}"> Clique aqui para voltar a tela de administração de Cercas eletrônicas. </a></em>

</div>
{% endblock %}

geofence/templates/edit_finish.html
{% extends "templates/base.html" %}

{%block title%}Infotrack - Edição de Cerca eletrônica {% endblock %}
{% block content %}


<div  class="main-form">
<h1><img class="icon" src="/media/img/equipment.png">Edição de Cerca eletrônica</h1>
<hr />
<h2>Cerca eletrônica editada com sucesso </h2>
<em>A Cerca eletrônica foi editada com sucesso. <a href="{% url geofence.views.index %}"> Clique aqui para voltar a tela de administração de Cercas eletrônicas. </a></em>

</div>
{% endblock %}

geofence/templates/home.html
{% extends "templates/base.html" %}

{% block head %}
<script type="text/javascript" src="http://maps.google.com/maps/api/js?libraries=geometry&sensor=false"></script>
<script type="text/javascript" src="/media/js/polygon(1.0).js"></script>
<script type="text/javascript" src="/media/js/geo.js"></script>
<script type="text/javascript" src="/media/js/geofence.js"></script>

{% endblock %}

{% block content %}
<div  class="main-form" id="geofencetool">

  <div style="float:left;width:20%;height:100%;">
   <p>Posição do cursor:</p>
   <p><span style="text-align:right;">Latitude:</span><input id="lat" type="text" style="margin: 5px 0 5px 5px;width: 118px;position:relative;left:10px;"></input></p>
   <p>Longitude:<input id="lng" type="text" style="margin: 5px 0 5px 4px;width: 118px;"></input></p>
   <div id="accordion" style="height:100%;">
     <h3><a href="#">Círculo</a></h3>
       <div>
         <p>Digite um raio e em seguida selecione um centro:</p><br/>
         <input type="text" id="radius" style="width:93px;"></input> metros <br/><br/><hr/><br/>
         <p align="center"><span class="table-button" id="circletool" style="cursor:pointer;padding:5px;">Marcar centro</span></p><br><br/>
         <p align="left">Ou digitar endereço do centro:</p>
         <form id="circlesubmit" style="margin-top:5px;width:auto;" action="#map">
           <p><input id="circlecenter" type="text"></input></p></br/>
         </form>
         <hr/><br/>
         <p>Área da círculo selecionado:</p>
         <input type="text" id="circlearea" style="width:93px;"></input> km<sup>2</sup>
         <br/><br/><hr/><br/>
         <input id="savecircle" type="submit" value="Salvar cerca eletrônica" style="float:right;"></input>
       </div>
     <h3><a href="#">Polígono</a></h3>
       <div>
         <p>Clique no botão abaixo para selecionar os vértices do polígono no mapa:</p><br/>
         <p align="center"><span class="table-button"  id="polygontool" style="cursor:pointer;padding:5px;">Traçar polígono</span></p><br><br/>
          <hr/><br/>
          <p>Ou digite os endereços para os pontos:</p><br/>
           <form id="polygonsubmit"  style="margin-top:5px;width:auto;" action="#map">
             <div id="polygoninputs">
               <input id="polygoninput1" type="text"></input>
               <input id="polygoninput2" type="text"></input>
               <input id="polygoninput3" type="text"></input>
             </div>
           <p><span id="addpoint"> + Adicionar ponto</span></p>
           <p align="center"><input type="submit" value="Traçar polígono"/></p>
           </form>
           <hr/><br/>
            <p>Área do polígono selecionado:</p>
            <input type="text" id="polygonarea" style="width:93px;"></input> km<sup>2</sup>
            <br/><br/><hr/><br/>
         	<p align="center"><input id="savepolygon" type="submit" value="Salvar cerca eletrônica"></p></div>
     <h3><a href="#">Rota</a></h3>
       <div>
         <p>Para selecionar a rota clique no botão abaixo e selecione os pontos desejados no mapa.</p><br/>
         <p align="center"><span class="table-button"  id="routetool"  style="cursor:pointer;padding:5px;">Selecionar rota</span></p><br/><br/>
         <p align="center"><span class="table-button"  id="routetool"  style="cursor:pointer;padding:5px;">Finalizar rota</span></p><br/><br/>
         <hr/><br/>
         <p>Ou digite os endereços para os pontos:</p><br/>
         <form id="routesubmit"  style="margin-top:5px;width:auto;" action="#map">
           <div id="routeinputs">
             <input id="routeinput1" type="text" />
             <input id="routeinput2" type="text" />
           </div>
         <p><span id="adddestiny"> + Adicionar destino</span></p>
         <p align="center"><input type="submit" value="Traçar rota" /></p>
         </form>
        
         <br/><br/><hr/><br/>
         
         <p>Distância da rota:</p><br/>
         <input id="routedistance" type="text" style="width:103px;"> km
         <p align="center"><input id="saveroute" type="submit" value="Salvar cerca eletrônica" /></p>
         
       </div>
    </div>
  </div>

   <div id="map" style="float:right;height:555px;width:79%;background-color:white;"></div>
   </div>
{% endblock %}

geofence/templates/home_old.html
{% extends "templates/base.html" %}

{% block head %}
<script type="text/javascript" src="http://maps.google.com/maps/api/js?libraries=geometry&sensor=false"></script>
<script type="text/javascript" src="/media/js/polygon(1.0).js"></script>
<script type="text/javascript" src="/media/js/geo.js"></script>
<script type="text/javascript" src="/media/js/geofence.js"></script>

{% endblock %}

{% block content %}
<div  class="main-form" id="geofencetool">

  <div style="float:left;width:20%;height:100%;">
   <p>Posição do cursor:</p>
   <p><span style="text-align:right;">Latitude:</span><input id="lat" type="text" style="margin: 5px 0 5px 5px;width: 118px;position:relative;left:10px;"></input></p>
   <p>Longitude:<input id="lng" type="text" style="margin: 5px 0 5px 4px;width: 118px;"></input></p>
   <div id="accordion" style="height:100%;">
     <h3><a href="#">Círculo</a></h3>
       <div>
         <p>Digite um raio e em seguida selecione um centro:</p><br/>
         <input type="text" id="radius" style="width:93px;"></input> metros <br/><br/><hr/><br/>
         <p align="center"><span class="table-button" id="circletool" style="cursor:pointer;padding:5px;">Marcar centro</span></p><br><br/>
         <p align="left">Ou digitar endereço do centro:</p>
         <form id="circlesubmit" style="margin-top:5px;width:auto;" action="#map">
           <p><input id="circlecenter" type="text"></input></p></br/>
         </form>
         <hr/><br/>
         <p>Área da círculo selecionado:</p>
         <input type="text" id="circlearea" style="width:93px;"></input> km<sup>2</sup>
         <br/><br/><hr/><br/>
         <input id="savecircle" type="submit" value="Salvar cerca eletrônica" style="float:right;"></input>
       </div>
     <h3><a href="#">Polígono</a></h3>
       <div>
         <p>Clique no botão abaixo para selecionar os vértices do polígono no mapa:</p><br/>
         <p align="center"><span class="table-button"  id="polygontool" style="cursor:pointer;padding:5px;">Traçar polígono</span></p><br><br/>
          <hr/><br/>
          <p>Ou digite os endereços para os pontos:</p><br/>
           <form id="polygonsubmit"  style="margin-top:5px;width:auto;" action="#map">
             <div id="polygoninputs">
               <input id="polygoninput1" type="text"></input>
               <input id="polygoninput2" type="text"></input>
               <input id="polygoninput3" type="text"></input>
             </div>
           <p><span id="addpoint"> + Adicionar ponto</span></p>
           <p align="center"><input type="submit" value="Traçar polígono"/></p>
           </form>
           <hr/><br/>
            <p>Área do polígono selecionado:</p>
            <input type="text" id="polygonarea" style="width:93px;"></input> km<sup>2</sup>
            <br/><br/><hr/><br/>
         	<p align="center"><input id="savepolygon" type="submit" value="Salvar cerca eletrônica"></p></div>
     <h3><a href="#">Rota</a></h3>
       <div>
         <p>Para selecionar a rota clique no botão abaixo e selecione os pontos desejados no mapa.</p><br/>
         <p align="center"><span class="table-button"  id="routetool"  style="cursor:pointer;padding:5px;">Selecionar rota</span></p><br/><br/>
         <p align="center"><span class="table-button"  id="routetool"  style="cursor:pointer;padding:5px;">Finalizar rota</span></p><br/><br/>
         <hr/><br/>
         <p>Ou digite os endereços para os pontos:</p><br/>
         <form id="routesubmit"  style="margin-top:5px;width:auto;" action="#map">
           <div id="routeinputs">
             <input id="routeinput1" type="text" />
             <input id="routeinput2" type="text" />
           </div>
         <p><span id="adddestiny"> + Adicionar destino</span></p>
         <p align="center"><input type="submit" value="Traçar rota" /></p>
         </form>
        
         <br/><br/><hr/><br/>
         
         <p>Distância da rota:</p><br/>
         <input id="routedistance" type="text" style="width:103px;"> km
         <p align="center"><input id="saveroute" type="submit" value="Salvar cerca eletrônica" /></p>
         
       </div>
    </div>
  </div>

   <div id="map" style="float:right;height:555px;width:79%;background-color:white;"></div>
   </div>
{% endblock %}

geofence/templates/index.html
{% extends "templates/base.html" %}

{% block head %}
<script src="/media/js/jquery.jqGrid.min.js" type="text/javascript"></script>
<script type="text/javascript" src="/media/js/jquery.treeTable.js"></script>
<link rel="stylesheet" href="/media/css/jquery.treeTable.css" type="text/css" media="screen" />
<script type="text/javascript">
    $(document).ready(function()  {
        $("#tree").treeTable({
            initialState: "expanded"
        });
    });  
</script>
{% endblock  %}

{% block content %}
<div id="config">
    <div class="main-form">
        <h1><img class="icon" src="/media/img/equipment.png">Gerenciamento de cercas eletrônicas</h1>
        <hr/>
        
        <h2>Lista de Cercas eletrônicas:</h2>
				<em>  </em>
				<div class="ui-jqgrid ui-widget ui-widget-content ui-corner-all" id="gbox_list4" dir="ltr"><div id="load_list4" class="loading ui-state-default ui-state-active" style="display: none;">Loading...</div><div class="ui-jqgrid-view" id="gview_list4"><div class="ui-jqgrid-titlebar ui-widget-header ui-corner-top ui-helper-clearfix"><a href="javascript:void(0)" role="link" class="ui-jqgrid-titlebar-close HeaderButton" style="right: 0px;"></a><p class="ui-jqgrid-title">&nbsp</p></div><div class="ui-state-default ui-jqgrid-hdiv"><div class="ui-jqgrid-hbox"><table cellspacing="0" cellpadding="0" border="0" aria-labelledby="gbox_list4" role="grid"  class="ui-jqgrid-htable">
				  
				  <thead>
				    
				    <tr role="rowheader" class="ui-jqgrid-labels">
				      <th class="ui-state-default ui-th-column ui-th-ltr" role="columnheader" id="list4_id" style="width: 40%;text-align:center;"><div id="jqgh_id" class="ui-jqgrid-sortable">Nome da cerca eletrônica</div></th>
				      	<th class="ui-state-default ui-th-column ui-th-ltr" role="columnheader" id="list4_id" style="width: 35%;text-align:center;"><div id="jqgh_id" class="ui-jqgrid-sortable">Tipo</div></th>
				      <th class="ui-state-default ui-th-column ui-th-ltr" role="columnheader" id="list4_invdate" style="width: 410px;text-align:center;"><div id="jqgh_invdate" class="ui-jqgrid-sortable">Ação</div></th></tr></thead></table></div></div><div class="ui-jqgrid-bdiv"><div style="margin-left:19px;"><div></div><table id="tree" cellspacing="0" cellpadding="0" border="0" id="list4" tabindex="1" role="grid" aria-multiselectable="true" aria-labelledby="gbox_list4" class="ui-jqgrid-btable" style="width:100%"><tbody>
				      
				      
				  <tr style="height: auto; width:100%" role="row" class="jqgfirstrow">
				  
				  <td style="height: 0px; width: 20px;" role="gridcell"></td>
				  
				  <td style="height: 0px; width:20px" role="gridcell"></td>
				  <td style="height: 0px; width:20px" role="gridcell"></td>
				  
				  
				  </tr>
				  
				  
				    {% for line in geofence_tree %}
				        {% if line.sysname %}
				        <tr style='width:5%;' id='node-{{line.id}}' {% if line.childof and line.sysid != request.session.system %}class='child-of-node-{{line.childof}}' {% endif %}>
				            <td style='width:25%;font-weight:bold;text-align:left;' >{{line.sysname}}</td>
				        </tr>
				        {% else %}
				        <tr style = 'width:5%' {% if line.childof %}class='child-of-node-{{line.childof}}'{% endif %}>
				            <td style='width:31%;text-align:left;' >{{line.geofence}}</td>
				            <td style='width:28%'>{{line.type}}</td>
				            <td style='width:28%'>{{line.timeend}}</td>
				            <td style='width:110px; padding-right:5px;'>
				                <a class='table-button' href='{% url geofence.views.edit line.id %}' >Editar</a>
				                <a class='table-button'  href='{% url geofence.views.delete line.id %}'>Apagar</a>
				            </td>
				        </tr>
				        {% endif %}
				    {% endfor %}
            </tbody></table></div></div></div><div id="rs_mlist4" class="ui-jqgrid-resize-mark">&nbsp;</div></div>
	         <div align="center" style="margin-top:10px;" id="actions">

                    <a href="{% url geofence.views.create%}">Criar cercas eletrônicas</a>
              </div>
      </div>
     
</div>
{% endblock %}

geofence/templates/multispectral.html
{% extends "templates/base.html" %}

{% block title %}
Infotrack - Cercas Eletrônicas
{% endblock %}

{% block head %}
<style type="text/css"> 
  #id_polygon_map { width: 600px; height: 400px; }
  #id_polygon_map .aligned label { float:inherit; }
  #id_polygon_admin_map { position: relative; vertical-align: top; float: left; }
  #id_polygon { display: none; }
  .olControlEditingToolbar .olControlModifyFeatureItemActive { 
     background-image: url("/static/admin/img/gis/move_vertex_on.png");
     background-repeat: no-repeat;
  }
  .olControlEditingToolbar .olControlModifyFeatureItemInactive { 
     background-image: url("/static/admin/img/gis/move_vertex_off.png");
     background-repeat: no-repeat;
  }
</style>
<script type="text/javascript" src="http://openlayers.org/api/OpenLayers.js"></script>
<script type="text/javascript" src="/media/js/geofence_circle.js"></script>
<script type="text/javascript" src="/media/js/geofence_polygon.js"></script>

<script type="text/javascript" src="/media/js/ajaxsend.js"></script>

<script type="text/javascript">
  
  
  
</script>

{% endblock %}

{% block content %}
<div id="geofence-tabs">
  <ul>
  		<li><a href="#tabs-1">Círculo</a></li>
  		<li><a href="#tabs-2">Polígono</a></li>
  		<li><a href="#tabs-3">Rota</a></li>
  	</ul>
  	<div id="tabs-1" style="overflow:hidden;">
  	  <div class="divsteps" style="margin-bottom:10px;overflow:hidden;">
    		<form id="step1" class="steps">
    		  <fieldset>
            <legend>1º Passo - Escolha um tamanho para o raio</legend>
              <p>Digite abaixo um tamanho para o raio em metros:</p>
               <p align="center"><input type="number" min="0" id="radius" placeholder="Digite um raio" autofocus></input> metros</p>
          </fieldset>
    		</form>
    		<form id="step2" class="steps">
    		  <fieldset>
            <legend>2º Passo - Escolha um local para o centro</legend>
            <p>Digite o endereço completo para o centro do círculo:</p>
            <p align="center"><input id="circlecenter" placeholder="Ex.:Rua Anchieta,Campinas" type="text"></input><input type="submit" value="Buscar endereço" style="padding:4px 12px;"></p>
          </fieldset>
    		</form>
    		<form id="step3" class="steps">
    		  <fieldset>
            <legend>3º Passo - Salvar cerca eletrônica</legend>
            <p>Após confirmar a visualização da cerca no mapa e sua área, digite um nome para a cerca e clique em salvar:</p>
            <p align="center"><b>Área da cerca eletrônica selecionada:</b></p><div align="center" id="circlearea"></div>
            <p align="center"><input id="circlename" placeholder="Digite um nome para a cerca" type="text" required></input><input id="circlesave" type="button" value="Salvar" style="padding:4px 12px;"></p>
          </fieldset>
    		</form>
  		</div>
  		<div id="map1" style="float:left;width:100%;height:300px;"></div>
  	</div>
  	<div id="tabs-2" style="overflow:hidden;">
  		<div class="divsteps" style="margin-bottom:10px;overflow:hidden;">
    		<form id="step1" class="steps" style="width:450px">
    		  <fieldset>
            <legend>1º Passo - Escolha os pontos para os vértices do polígono</legend>
              <p>Digite o endereço para os vértices (mínimo 3):</p>
              <div id="polygoninputs" style="overflow: auto; height: 81px;">
                <ol>
                  <li><p align="center"><span>1.</span><input id="polygoninput1" placeholder="Ex.:Rua Anchieta,Campinas" type="text"></input></p>
                  <li><p align="center"><span>2.</span><input id="polygoninput2" placeholder="Ex.:Rua Anchieta,Campinas" type="text"></input></p>
                  <li><p align="center"><span>3.</span><input id="polygoninput3" placeholder="Ex.:Rua Anchieta,Campinas" type="text"></input></p>
                </ol>
               </div>
               <p align="center"><span id="addpoint"> + Adicionar ponto</span></p>
               <p align="center"><input type="submit" value="Montar polígono com os endereços acima"/></p>
          </fieldset>
    		</form>
    		<form id="step2" class="steps" style="width:450px">
    		  <fieldset>
            <legend>2º Passo - Salvar cerca eletrônica</legend>
             <p>Após confirmar a visualização da cerca no mapa e sua área, digite um nome para a cerca e clique em salvar:</p>
              <p align="center"><b>Área da cerca eletrônica selecionada:</b></p><div align="center" id="polygonarea"></div>
              <p align="center"><input id="polygoname" placeholder="Digite um nome para a cerca" type="text" required></input><input id="polygonsave" type="button" value="Salvar" style="padding:4px 12px;"></p>
          </fieldset>
    		</form>
  		</div>
  		<div id="map2" style="float:left;width:100%;height:300px;"></div>
  	</div>
  	<div id="tabs-3">
  		<p>Mauris eleifend est et turpis. Duis id erat. Suspendisse potenti. Aliquam vulputate, pede vel vehicula accumsan, mi neque rutrum erat, eu congue orci lorem eget lorem. Vestibulum non ante. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Fusce sodales. Quisque eu urna vel enim commodo pellentesque. Praesent eu risus hendrerit ligula tempus pretium. Curabitur lorem enim, pretium nec, feugiat nec, luctus a, lacus.</p>
  		<p>Duis cursus. Maecenas ligula eros, blandit nec, pharetra at, semper at, magna. Nullam ac lacus. Nulla facilisi. Praesent viverra justo vitae neque. Praesent blandit adipiscing velit. Suspendisse potenti. Donec mattis, pede vel pharetra blandit, magna ligula faucibus eros, id euismod lacus dolor eget odio. Nam scelerisque. Donec non libero sed nulla mattis commodo. Ut sagittis. Donec nisi lectus, feugiat porttitor, tempor ac, tempor vitae, pede. Aenean vehicula velit eu tellus interdum rutrum. Maecenas commodo. Pellentesque nec elit. Fusce in lacus. Vivamus a libero vitae lectus hendrerit hendrerit.</p>
  	</div>
</div>
{% endblock %}